class AppRoutes {
  // welcome page or on boarding....
  static const initialRoutes = "/";

  //application screen...
  static const appDashboardRoutes = "dashBoard";

  //sign In screen....
  static const signInRoutes = "signIn";

  //sing up screen...
  static const signUpRoutes = "signUp";
}
