class AppRoutes {
  // welcome page or on boarding....
  static const initialRoutes = "/";

  //application screen...
  static const appDashboardRoutes = "/";

  //sign In screen....
  static const signInRoutes = "/";

  //sing up screen...
  static const signUpRoutes = "/";
}
